
export const stockList = {"OBLN":"Obalon Therapeutics Inc","GEVO":"Gevo Inc","PBR":"Petroleo Brasileiro S.A. Petrobras - ADR","BB":"BlackBerry Ltd","BABA":"Alibaba Group Holding Ltd - ADR","SENS":"Senseonics Holdings Inc","MSFT":"Microsoft Corporation","BNGO":"Bionano Genomics Inc","AMC":"AMC Entertainment Holdings Inc - Class A","GM":"General Motors Company","PLUG":"Plug Power Inc","TME":"Tencent Music Entertainment Group - ADR","ACRX":"Acelrx Pharmaceuticals Inc","XLF":"SSgA Active Trust - SSgA Financial Select Sector SPDR","AAPL":"Apple Inc","NFLX":"NetFlix Inc","F":"Ford Motor Co.","FB":"Facebook Inc - Class A",
    "ZNGA":"Zynga Inc - Class A","BAC":"Bank Of America Corp.","PFE":"Pfizer Inc.","XLU":"SSgA Active Trust - SSgA Utilities Select Sector SPDR","ETRN":"Equitrans Midstream Corporation","FCEL":"Fuelcell Energy Inc","MS":"Morgan Stanley","MU":"Micron Technology Inc.","EEM":"BlackRock Institutional Trust Company N.A. - BTC iShares MSCI Emerging","VZ":"Verizon Communications Inc","NIO":"NIO Inc - ADR","NLY":"Annaly Capital Management Inc","ADMP":"Adamis Pharmaceuticals Corp","INUV":"Inuvo Inc","TWTR":"Twitter Inc","TZPSU":"TZP Strategies Acquisition Corp - Units (1 Ord Class A & 1/3 War)","NOK":"Nokia Corp - ADR","RIG":"Transocean Ltd","AMD":"Advanced Micro Devices Inc.",
    "HYG":"BlackRock Institutional Trust Company N.A. - BTC iShares iBoxx USD Hig","TRXC":"TransEnterix Inc","TSM":"Taiwan Semiconductor Manufacturing - ADR","PCG":"PG&E Corp.","MRO":"Marathon Oil Corporation","PG":"Procter & Gamble Co.","GRTS":"Gritstone Oncology Inc","ET":"Energy Transfer LP - Unit","ACRS":"Aclaris Therapeutics Inc","SCHW":"Charles Schwab Corp.","WFC":"Wells Fargo & Co.","UBER":"Uber Technologies Inc","BK":"Bank Of New York Mellon Corp","TSLA":"Tesla Inc","SPY":"SSgA Active Trust - SSGA SPDR S&P 500","FCX":"Freeport-McMoRan Inc","GME":"Gamestop Corporation - Class A","IVZ":"Invesco Ltd","GSAT":"Globalstar Inc.",
    "CCL":"Carnival Corp. (Paired Stock)","VRT":"Vertiv Holdings Co - Class A","JPM":"JPMorgan Chase & Co.","KO":"Coca-Cola Co","GE":"General Electric Co.","V":"Visa Inc - Class A","JD":"JD.com Inc - ADR","INTC":"Intel Corp.","GOOS":"Canada Goose Holdings Inc (Subord Vot Shs)","VALE":"Vale S.A. - ADR","BE":"Bloom Energy Corp - Class A","CX":"Cemex S.A.B. De C.V. - ADR","FUTU":"Futu Holdings Ltd - ADR","IQ":"iQIYI Inc - ADR","LAC":"Lithium Americas Corp","CRM":"Salesforce.Com Inc","SNAP":"Snap Inc - Class A","T":"AT&T, Inc.","AG":"First Majestic Silver Corporation","CCO":"Clear Channel Outdoor Holdings Inc.",
    "GMBTU":"Queens Gambit Growth Capital - Units (1 Ord Class A & 1/3 War)","DD":"DuPont de Nemours Inc","QQQ":"Invesco Capital Management LLC - Invesco QQQ Trust Series 1","BIDU":"Baidu Inc - ADR","C":"Citigroup Inc","LLY":"Lilly(Eli) & Co","FUBO":"fuboTV Inc","FXI":"BlackRock Institutional Trust Company N.A. - BTC iShares China Large-C","MRVL":"Marvell Technology Group Ltd","AAL":"American Airlines Group Inc","GSX":"Gsx Techedu Inc - ADR","USB":"U.S. Bancorp.","AZN":"Astrazeneca plc - ADR","DISCA":"Discovery Inc - Class A","XOM":"Exxon Mobil Corp.","CSCO":"Cisco Systems, Inc.","OSTRU":"Oyster Enterprises Acquisition Corp - Units (1 Ord Class A & 1/2 War)",
    "SU":"Suncor Energy, Inc.","PYPL":"PayPal Holdings Inc","QCOM":"Qualcomm, Inc.","AMAT":"Applied Materials Inc.","CLNE":"Clean Energy Fuels Corp","HAL":"Halliburton Co.","EH":"EHang Holdings Ltd - ADR","DFS":"Discover Financial Services","BKR":"Baker Hughes Co - Class A","BLRX":"Bioline Rx Ltd - ADR","PDD":"Pinduoduo Inc - ADR","CCIV":"Churchill Capital Corp IV - Class A","CVX":"Chevron Corp.","PLTR":"Palantir Technologies Inc - Class A","ABBV":"Abbvie Inc","STNE":"StoneCo Ltd - Class A","MARA":"Marathon Patent Group Inc","LU":"Lufax Holding Ltd - ADR","WORK":"Slack Technologies Inc - Class A",
    "RTP":"Reinvent Technology Partners - Class A","MRK":"Merck & Co Inc","AES":"AES Corp.","SLB":"Schlumberger Ltd.","FAST":"Fastenal Co.","XPEV":"XPeng Inc - ADR","MA":"Mastercard Incorporated - Class A","LEGOU":"Legato Merger Corp - Units (1 Ord & 1 War)","HBAN":"Huntington Bancshares, Inc.","ONEM":"1life Healthcare Inc","K":"Kellogg Co","GOLD":"Barrick Gold Corp.","GILD":"Gilead Sciences, Inc.","UMC":"United Micro Electronics - ADR","BRK.B":"Berkshire Hathaway Inc. - Class B","VXX":"Barclays Bank PLC - ZC SP ETN REDEEM 23/01/2048 USD 27.193879 - Ser A ","SIRI":"Sirius XM Holdings Inc","OXY":"Occidental Petroleum Corp.",
    "CMCSA":"Comcast Corp - Class A","KAR":"KAR Auction Services Inc","RUN":"Sunrun Inc","COP":"Conoco Phillips","GDX":"VanEck Vectors ETF Trust - VanEck Vectors Gold Miners ETF","IXUS":"BlackRock Institutional Trust Company N.A. - BTC iShares Core MSCI Tot","PINS":"Pinterest Inc - Class A","CL":"Colgate-Palmolive Co.","ABNB":"Airbnb Inc - Class A","LI":"Li Auto Inc - ADR","TMDI":"Titan Medical Inc","SWN":"Southwestern Energy Company","CSX":"CSX Corp.","KMI":"Kinder Morgan Inc - Class P","IPOE":"Social Capital Hedosophia Holdings Corp V - Class A","AUY":"Yamana Gold Inc.","PK":"Park Hotels & Resorts Inc","NEE":"NextEra Energy Inc",
    "DKNG":"DraftKings Inc - Class A","DT":"Dynatrace Inc","FSLY":"Fastly Inc - Class A","SFIX":"Stitch Fix Inc - Class A","EA":"Electronic Arts, Inc.","COHR":"Coherent Inc.","TDOC":"Teladoc Health Inc","DARE":"Dare Bioscience Inc","TELL":"Tellurian Inc","CCJ":"Cameco Corp.","LITE":"Lumentum Holdings Inc","AT":"Atlantic Power Corp.","PLTK":"Playtika Holding Corp","VIAC":"ViacomCBS Inc - Class B","DVN":"Devon Energy Corp.","HPQ":"HP Inc","EWJ":"BlackRock Institutional Trust Company N.A. - BTC iShares MSCI Japan ET","DBX":"Dropbox Inc - Class A","JNJ":"Johnson & Johnson","FTCH":"Farfetch Ltd - Class A",
    "LVS":"Las Vegas Sands Corp","ADBE":"Adobe Inc","DIS":"Walt Disney Co (The)","BEKE":"KE Holdings Inc - ADR","BA":"Boeing Co.","BSX":"Boston Scientific Corp.","IBM":"International Business Machines Corp.","SKLZ":"Skillz Inc - Class A","BKLN":"Invesco Capital Management LLC - Invesco Senior Loan ETF","PHM":"PulteGroup Inc","FLEX":"Flex Ltd","VNT":"Vontier Corporation","KR":"Kroger Co.","SYF":"Synchrony Financial","SRNE":"Sorrento Therapeutics Inc","TJX":"TJX Companies, Inc.","AA":"Alcoa Corp","YPF":"YPF - ADR","MCHI":"BlackRock Institutional Trust Company N.A. - BTC iShares MSCI China ET","SESN":"Sesen Bio Inc.",
    "BMY":"Bristol-Myers Squibb Co.","GPS":"Gap, Inc.","RRC":"Range Resources Corp","AUPH":"Aurinia Pharmaceuticals Inc","AVGR":"Avinger Inc","CVET":"Covetrus Inc","TXN":"Texas Instruments Inc.","HTH":"Hilltop Holdings Inc","EQT":"EQT Corp","AEO":"American Eagle Outfitters Inc.","ZM":"Zoom Video Communications Inc - Class A"}

export const symbolList = ["OBLN","GEVO","PBR","BB","BABA","SENS","MSFT","BNGO","AMC","GM","PLUG","TME","ACRX","XLF","AAPL","NFLX",
    "F","FB","ZNGA","BAC","PFE","XLU","ETRN","FCEL","MS","MU","EEM","VZ","NIO","NLY","ADMP","INUV","TWTR","TZPSU","NOK","RIG","AMD","HYG",
    "TRXC","TSM","PCG","MRO","PG","GRTS","ET","ACRS","SCHW","WFC","UBER","BK","TSLA","SPY","FCX","GME","IVZ","GSAT","CCL","VRT","JPM","KO",
    "GE","V","JD","INTC","GOOS","VALE","BE","CX","FUTU","IQ","LAC","CRM","SNAP","T","AG","CCO","GMBTU","DD","QQQ","BIDU","C","LLY","FUBO",
    "FXI","MRVL","AAL","GSX","USB","AZN","DISCA","XOM","CSCO","OSTRU","SU","PYPL","QCOM","AMAT","CLNE","HAL","EH","DFS","BKR","BLRX","PDD",
    "CCIV","CVX","PLTR","ABBV","STNE","MARA","LU","WORK","RTP","MRK","AES","SLB","FAST","XPEV","MA","LEGOU","HBAN","ONEM","K","GOLD","GILD",
    "UMC","BRK.B","VXX","SIRI","OXY","CMCSA","KAR","RUN","COP","GDX","IXUS","PINS","CL","ABNB","LI","TMDI","SWN","CSX","KMI","IPOE","AUY","PK",
    "NEE","DKNG","DT","FSLY","SFIX","EA","COHR","TDOC","DARE","TELL","CCJ","LITE","AT","PLTK","VIAC","DVN","HPQ","EWJ","DBX","JNJ","FTCH","LVS",
    "ADBE","DIS","BEKE","BA","BSX","IBM","SKLZ","BKLN","PHM","FLEX","VNT","KR","SYF","SRNE","TJX","AA","YPF","MCHI","SESN","BMY","GPS","RRC",
    "AUPH","AVGR","CVET","TXN","HTH","EQT","AEO","ZM"]